name: iOS 15 Test

on:
  pull_request:
  push:
    branches: [ master ]

env:
  DEVELOPER_DIR: /Applications/Xcode_13.3.1.app/Contents/Developer

jobs:
  build:
    runs-on: macos-12.3

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install Slather
        run: gem install slather

      - name: iOS 15 Testing
        run: xcodebuild CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES -destination "platform=iOS Simulator,name=iPhone 13,OS=15.4" -scheme "SMAUpdatesAvailable-Tests" test

      - name: Run Slather
        run: slather

      - name: Verify Coverage
        run: curl -s https://codecov.io/bash | bash -s - -v -f test-reports/cobertura.xml -X coveragepy -X gcov -X xcode
